# Generated by Django 2.0.5 on 2020-04-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='img',
            new_name='image',
        ),
    ]
